### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by marta-sd** [dizak/mothulity_django#1]
I can't tell if all this django-related things are implemented properly, so I focused on more general stuff. I was quite picky, so there's a lot of comments, but in general I think it's clear and nicely written :)

## `forms.py`

- I don't understand this label:
https://github.com/dizak/mothulity_django/blob/beb4ee105fa96c2dac7bcfb3926c69c3d69bbf88/forms.py#L48-L49

- Also this one isn't obvious for me:
https://github.com/dizak/mothulity_django/blob/beb4ee105fa96c2dac7bcfb3926c69c3d69bbf88/forms.py#L63-L64
I know what bootstrap value is, but I'm not sure how this parameter will affect the results.

- It's not crucial at the moment, but I think you should add more validation here. I mean something like [this](https://docs.djangoproject.com/en/1.11/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other), to make sure all this max/min parameters make sense (e.g. `max_length >= min_length` and both are non-negative etc)

## `models.py`

- Is this a bug or a feature?
https://github.com/dizak/mothulity_django/blob/beb4ee105fa96c2dac7bcfb3926c69c3d69bbf88/models.py#L21-L22

## `utils.py`
- It looks like a file object to me (it has `chunks` method)
https://github.com/dizak/mothulity_django/blob/beb4ee105fa96c2dac7bcfb3926c69c3d69bbf88/utils.py#L15

- It would be nice to have `chunk_size` parameter here
https://github.com/dizak/mothulity_django/blob/beb4ee105fa96c2dac7bcfb3926c69c3d69bbf88/utils.py#L21

- No, this time it's `input_str` :)
https://github.com/dizak/mothulity_django/blob/beb4ee105fa96c2dac7bcfb3926c69c3d69bbf88/utils.py#L79-L80

- Are there any other elements in `s_line`?
https://github.com/dizak/mothulity_django/blob/beb4ee105fa96c2dac7bcfb3926c69c3d69bbf88/utils.py#L92
If no, I think it's a good idea to add an assertion here (`assert len(s_line) == 1`). If yes, why do we ignore them?

- What if there is no error, but it's a different file format?
https://github.com/dizak/mothulity_django/blob/beb4ee105fa96c2dac7bcfb3926c69c3d69bbf88/utils.py#L134-L138
One solution is to add `else`, but if think it'll be prettier to remove this `if` and just return:
```python
    try:
        return (sniff(input_file)[0] == file_frmt)
    except Exception as e:
        return False
```

- Is there a reason you don'y use `items()` here?
https://github.com/dizak/mothulity_django/blob/beb4ee105fa96c2dac7bcfb3926c69c3d69bbf88/utils.py#L169-L171
I mean something like this:
```python
moth_opt_str = " ".join(["--{} {}".format(k, v) for k, v in moth_options.items()])
```

## `views.py`

- This function needs some comments, it's not clear what's going on here
https://github.com/dizak/mothulity_django/blob/beb4ee105fa96c2dac7bcfb3926c69c3d69bbf88/views.py#L14

- I'm a django noob, but what happens if this form is not valid?
https://github.com/dizak/mothulity_django/blob/beb4ee105fa96c2dac7bcfb3926c69c3d69bbf88/views.py#L19
I was thinking if it's possible to change the structure of this whole part to make it less nested, something like:
```python
        if not form.is_valid():
            return render(request,     # or whatever it should in such cases
                  "mothulity/index.html.jj2",
                  {"form": form})

        job_id = uuid.uuid4()
        upld_dir = "{}{}/".format(settings.MEDIA_URL,
                                  job_id)
 ...
```

- \m/ Have you tried 600?
https://github.com/dizak/mothulity_django/blob/beb4ee105fa96c2dac7bcfb3926c69c3d69bbf88/views.py#L30

- I think you can use `if not` here
https://github.com/dizak/mothulity_django/blob/beb4ee105fa96c2dac7bcfb3926c69c3d69bbf88/views.py#L31-L41
I mean:
```python
                if not utils.sniff_file("{}{}".format(upld_dir,
                                                  upfile), "fastq"):
                    os.system("rm -r {}".format(upld_dir))
                    form = FileFieldForm()
                    return render(request,
                                  "mothulity/index.html.jj2",
                                  {"form": form,
                                   "upload_error": True})
```

- You don't use `seqs_stats`, but I guess results are saved somewhere?
https://github.com/dizak/mothulity_django/blob/beb4ee105fa96c2dac7bcfb3926c69c3d69bbf88/views.py#L54

- Can't we use something like `sub_data = job.submissiondata_set.create(**request.POST)` here?
https://github.com/dizak/mothulity_django/blob/beb4ee105fa96c2dac7bcfb3926c69c3d69bbf88/views.py#L74-L85

- I think it's easy to introduce a bug here (lot of hard-coded names)
https://github.com/dizak/mothulity_django/blob/beb4ee105fa96c2dac7bcfb3926c69c3d69bbf88/views.py#L88-L98
If it's possible to get `sub_data` attributes by their name, consider converting names automatically:
```python
    moth_cmd_dict = {"run": "sbatch",
                     "output-dir": headnode_dir}
    for attr_name in ["job-name", "notify-email", "max-ambig", "max-homop",
                      "min-length", "max-length", "min-overlap",
                      "screen-criteria", "chop-length", "precluster-diffs",
                      "classify-seqs-cutoff"]:
        moth_cmd_dict[attr_name] = sub_data[attr_name.replace('-', '_')]

```

**Comment by dizak** [comment]
This review helped me a lot :+1: :100: Begging for more

By the time, quite a lot has changed.
Now, the django part only saves files on the web-server and gathers info about analysis parameters.
Once every given period of time, sched.py takes what is in the database and submits it to the computing-server.

#  forms.py
> - I don't understand this label:

I hope it is quite clear now.

https://github.com/dizak/mothulity_django/blob/0b1ca535b09724bb424c12c07827beec99537e9a/forms.py#L55-L57

https://github.com/dizak/mothulity_django/blob/0b1ca535b09724bb424c12c07827beec99537e9a/forms.py#L71-L74

> It's not crucial at the moment, but I think you should add more validation here. I mean something like this, to make sure all this max/min parameters make sense (e.g. max_length >= min_length and both are non-negative etc)

It IS crucial

https://github.com/dizak/mothulity_django/blob/0b1ca535b09724bb424c12c07827beec99537e9a/forms.py#L84-L93

https://github.com/dizak/mothulity_django/blob/0b1ca535b09724bb424c12c07827beec99537e9a/views.py#L98-L100

https://github.com/dizak/mothulity_django/blob/0b1ca535b09724bb424c12c07827beec99537e9a/views.py#L119-L124

# models.py
> Is this a bug or a feature?

[Feature](https://docs.djangoproject.com/en/2.0/intro/tutorial02/)

# utils.py

> It looks like a file object to me (it has chunks method)
It would be nice to have chunk_size parameter here
No, this time it's input_str :)

Modest and humble servant of yours

https://github.com/dizak/mothulity_django/blob/ce502077981555888a97c5b59217d66d06ea373e/utils.py#L15-L32

> Are there any other elements in s_line?
If no, I think it's a good idea to add an assertion here (assert len(s_line) == 1). If yes, why do we ignore them?

Once again you are right!

https://github.com/dizak/mothulity_django/blob/ce502077981555888a97c5b59217d66d06ea373e/utils.py#L8-L12

https://github.com/dizak/mothulity_django/blob/ce502077981555888a97c5b59217d66d06ea373e/utils.py#L106-L108

> What if there is no error, but it's a different file format?

It IS an error if it is a different file format. I mean it.

> Is there a reason you don'y use items() here?

Just me stupid

https://github.com/dizak/mothulity_django/blob/ce502077981555888a97c5b59217d66d06ea373e/utils.py#L216-L217

# views.py

> This function needs some comments, it's not clear what's going on here

Function without documentation is a broken function

https://github.com/dizak/mothulity_django/blob/ce502077981555888a97c5b59217d66d06ea373e/views.py#L17-L31

> I was thinking if it's possible to change the structure of this whole part to make it less nested,

If less nested then Generic Views but I don't feel it is the moment yet.

> I'm a django noob, but what happens if this form is not valid?

You are allowed to punish the users, like here, showing these dummies BIG RED ERROR!

https://github.com/dizak/mothulity_django/blob/ce502077981555888a97c5b59217d66d06ea373e/views.py#L119-L124

https://github.com/dizak/mothulity_django/blob/ce502077981555888a97c5b59217d66d06ea373e/templates/mothulity/options.html.jj2#L6-L14

But in this case it's just for detecting whether a user already uploaded files or not (else means render clean and fresh upload page). Anyway, it is supposed to look like that.

> \m/ Have you tried 600?

I will wait for the production server with it.

> I think you can use if not here

Thank you, pretty and simple. Still, I like the bool to be so explicite... Is it bad to keep it?..

https://github.com/dizak/mothulity_django/blob/ce502077981555888a97c5b59217d66d06ea373e/views.py#L47-L49

> You don't use seqs_stats, but I guess results are saved somewhere?

It is saved to database. Is is very useful when deciding whether submit to n or phi nodes

> Can't we use something like sub_data = job.submissiondata_set.create(**request.POST) here?

There are other kwargs in request.POST and I wanted to see exactly what happens. It will probably be amended in the future.

> I think it's easy to introduce a bug here (lot of hard-coded names)
> If it's possible to get sub_data attributes by their name, consider converting names automatically

Thank you :)

https://github.com/dizak/mothulity_django/blob/ce502077981555888a97c5b59217d66d06ea373e/utils.py#L211-L220

https://github.com/dizak/mothulity_django/blob/ce502077981555888a97c5b59217d66d06ea373e/sched.py#L95

https://github.com/dizak/mothulity_django/blob/ce502077981555888a97c5b59217d66d06ea373e/sched.py#L95

**Comment by marta-sd** [comment]
I like the changes :+1: 

I have one more comment: I think you should verify all your assumptions about the input data in `OptionsForm`, it's not idiot-proof at the moment. It looks like all numerical values should be non-negative and also `screen_criteria` and `classify_seqs_cutoff`(?) should be between 0 and 100, but currently the user can set any of these fields to -100. I think it's easy to fix with built-in [validators](https://docs.djangoproject.com/en/dev/ref/validators/)
